require("custom.opts")
require("custom.binds")
require("custom.cmd")
require("custom.statusline")
require("custom.fzf")
require("custom.nexus")
require("custom.switch")
-- require("custom.anki")
-- require("custom.nexus")
-- require("custom.comp")
-- require("custom.debug")
-- require("custom.lua_scratch")
