require("custom.opts")
require("custom.binds")
require("custom.autocmd")
require("custom.cmd")
require("custom.statusline")
require("custom.filetree")
require("custom.fzf")
require("custom.debug")
require("custom.nexus")
-- require("custom.comp")
